name: Create GitHub release and publish to npm

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    if: github.repository == 'ricochetuniverse/nuvelocity-unpacker-web'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Install .NET workload
        run: dotnet workload install wasm-tools-net8

      - name: Publish .NET app
        run: dotnet publish -c Release src/

      - name: Create zip for GitHub release
        run: |
          zip -rj "dotnet-wasm.zip" web/public/dotnet/wwwroot/_framework/
          mkdir npm/dotnet/
          cp -r web/public/dotnet/wwwroot/_framework/ npm/dotnet/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dotnet-wasm.zip

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: npm/package-lock.json

      - name: Publish
        run: npm publish --provenance --access public
        working-directory: ./npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
