name: Create GitHub release and publish to npm

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: github.repository == 'ricochetuniverse/nuvelocity-unpacker-web'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # https://github.com/actions/checkout/releases/tag/v6.0.3
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # https://github.com/actions/setup-dotnet/releases/tag/v5.3.0
        with:
          dotnet-version: '9.0'
          workloads: wasm-tools-net8

      - name: Publish .NET app
        run: dotnet publish -c Release src/

      # GitHub releases
      - name: Create zip for GitHub release
        run: |
          zip -rj "dotnet-wasm.zip" web/public/dotnet/wwwroot/_framework/
          mkdir npm/dotnet/
          cp -r web/public/dotnet/wwwroot/_framework/ npm/dotnet/

      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # https://github.com/softprops/action-gh-release/releases/tag/v3.0.0
        with:
          files: |
            dotnet-wasm.zip

      # npm
      # https://docs.npmjs.com/trusted-publishers
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # https://github.com/actions/setup-node/releases/tag/v6.4.0
        with:
          node-version: lts/*
          # cache: 'npm'
          # cache-dependency-path: npm/package-lock.json
          package-manager-cache: false # never use caching in release builds

      - name: Publish
        run: npm stage publish
        working-directory: ./npm
