name: Deploy static content to GitHub Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # https://github.com/actions/checkout/releases/tag/v6.0.3
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # https://github.com/actions/setup-dotnet/releases/tag/v5.3.0
        with:
          dotnet-version: '9.0'
          workloads: wasm-tools-net8

      - name: Publish .NET app
        run: dotnet publish -c Release src/

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # https://github.com/actions/setup-node/releases/tag/v6.4.0
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./web

      - name: Build website
        run: npm run build
        working-directory: ./web

      - name: Set up Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # https://github.com/actions/configure-pages/releases/tag/v6.0.0

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # https://github.com/actions/upload-pages-artifact/releases/tag/v5.0.0
        with:
          path: './web/dist'

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # https://github.com/actions/deploy-pages/releases/tag/v5.0.0
