name: Deploy static content to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: github.repository == 'ricochetuniverse/nuvelocity-unpacker-web'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Install .NET workload
        run: dotnet workload install wasm-tools-net8

      - name: Publish .NET app
        run: dotnet publish -c Release src/

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./web

      - name: Build website
        run: npm run build
        working-directory: ./web

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
